import assert from 'node:assert/strict';
import fs from 'node:fs';
import {chromium} from 'playwright-core';
const base=process.env.TRACKME_URL || process.env.STUDYTRACK_URL || 'http://127.0.0.1:4174';
const out='/tmp/trackme-categories';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050},timezoneId:'Asia/Kolkata',reducedMotion:'reduce',hasTouch:true});
await page.clock.setFixedTime(new Date('2026-09-17T12:00:00Z'));
page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async route=>{await page.goto(base+'/'+route);await page.locator('.route-frame').waitFor();};
const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('studytrack.workspace.v1')));
const category=()=>page.getByRole('combobox',{name:'Category',exact:true});
const search=()=>page.getByRole('combobox',{name:'Search categories',exact:true});
const option=name=>page.getByRole('option',{name,exact:true});
const openTask=async()=>{await page.getByRole('button',{name:'New Task',exact:true}).click();await page.getByRole('dialog').waitFor();};
try {
 await go('tasks');const seed=await data();
 seed.customCategories=['Physics','physics',...Array.from({length:16},(_,i)=>'Topic '+String(i+1).padStart(2,'0'))];
 seed.tasks=[{id:'legacy',title:'Legacy study',description:'',category:'PHYSICS',status:'todo',priority:'medium',dueDate:'2026-09-17',plannedDate:'2026-09-17',createdAt:'2026-09-16T10:00:00Z',estimatedPomodoros:2,actualPomodoros:0,subtasks:[]},{id:'tasksource',title:'Task-only category',description:'',category:'Calculus',status:'todo',priority:'medium',dueDate:'2026-09-17',plannedDate:'2026-09-17',createdAt:'2026-09-16T10:00:00Z',estimatedPomodoros:2,actualPomodoros:0,subtasks:[]}];
 seed.events=[{id:'event',title:'Exam',category:'Exam prep',date:'2026-09-17',color:'#a7c993'}];
 seed.sessions=[{id:'record',type:'focus',category:'Botany',startTime:'2026-09-17T07:00:00Z',endTime:'2026-09-17T07:25:00Z',actualDuration:25,plannedDuration:25,completed:true,interrupted:false}];
 await page.evaluate(seed=>localStorage.setItem('studytrack.workspace.v1',JSON.stringify(seed)),seed);await go('tasks');
 await openTask();await page.getByLabel('Task title',{exact:true}).fill('New categorized task');await category().click();
 for(const name of ['General','Revision','Physics','Calculus','Exam prep','Botany'])assert.equal(await option(name).count(),1,name);
 assert.equal(await page.getByRole('option',{name:/^physics$/i}).count(),1);
 await search().fill('prep');await page.keyboard.press('Enter');assert.equal(await category().innerText(),'Exam prep');
 await category().click();await search().fill('Discard this search');await page.keyboard.press('Escape');assert.equal(await category().innerText(),'Exam prep');assert.equal(await page.getByRole('dialog').count(),1);
 await category().click();await search().fill('No category selected');await page.keyboard.press('Tab');assert.equal(await category().innerText(),'Exam prep');assert.equal(await page.getByRole('listbox').count(),0);assert(await page.getByLabel('Estimated Pomodoros',{exact:true}).evaluate(el=>el===document.activeElement));
 await category().click();await search().fill('Organic chemistry');await option('Create “Organic chemistry”').click();assert.equal(await category().innerText(),'Organic chemistry');assert((await data()).customCategories.includes('Organic chemistry'));
 await category().click();await search().fill('organic CHEMISTRY');assert.equal(await page.getByRole('option',{name:/Create/}).count(),0);await page.keyboard.press('Enter');
 await page.getByRole('button',{name:'Create task',exact:true}).click();assert.equal((await data()).tasks.find(t=>t.title==='New categorized task').category,'Organic chemistry');
 await page.getByRole('button',{name:'Legacy study',exact:true}).click();assert.equal(await category().innerText(),'PHYSICS');await category().click();assert.equal(await option('PHYSICS').count(),1);await option('PHYSICS').click();await page.getByRole('button',{name:'Save task',exact:true}).click();assert.equal((await data()).tasks.find(t=>t.id==='legacy').category,'PHYSICS');
 console.log('PASS shared catalog from all sources, deduplication, keyboard selection, Escape/Tab, inline creation, and legacy editing');

 await go('calendar');await page.getByRole('button',{name:'New event',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Chemistry test');await category().click();await option('Organic chemistry').click();await page.getByRole('button',{name:'Save Event',exact:true}).click();assert.equal((await data()).events.find(e=>e.title==='Chemistry test').category,'Organic chemistry');
 await page.getByRole('button',{name:'Add task for selected day',exact:true}).click();await category().click();await option('Botany').click();await page.getByLabel('Task title',{exact:true}).fill('Calendar botany');await page.getByRole('button',{name:'Create task',exact:true}).click();assert.equal((await data()).tasks.find(t=>t.title==='Calendar botany').category,'Botany');
 await go('history');await page.getByRole('button',{name:'Log study',exact:true}).click();await page.getByLabel('Study date',{exact:true}).fill('2026-09-16');await page.getByLabel('Start time',{exact:true}).fill('10:00');
 const subject=page.getByRole('combobox',{name:'Subject or category',exact:true});await subject.click();await search().fill('Organic chemistry');await page.keyboard.press('Enter');assert.equal(await page.getByRole('dialog').count(),1);await page.getByRole('button',{name:'Save study block',exact:true}).click();assert.equal((await data()).sessions[0].category,'Organic chemistry');
 await go('timer');await category().click();for(const name of ['Exam prep','Botany','Organic chemistry'])assert.equal(await option(name).count(),1);await option('Organic chemistry').click();assert.equal(await category().innerText(),'Organic chemistry');
 await page.getByRole('button',{name:'Start timer',exact:true}).click();await page.getByRole('button',{name:'Pause timer',exact:true}).click();assert(await category().isDisabled());
 await page.getByRole('button',{name:'Open command palette',exact:true}).click();await page.getByRole('textbox',{name:'Search commands',exact:true}).fill('Manage study categories');await page.keyboard.press('Enter');await page.waitForURL('**/settings#settings-categories');await page.waitForFunction(()=>document.activeElement?.id==='settings-categories');
 const catalogRows=page.locator('.category-catalog-row');
 for(const name of ['General','Revision','Physics','Calculus','Exam prep','Botany','Organic chemistry'])assert.equal(await catalogRows.filter({has:page.getByText(name,{exact:true})}).count(),1,name);
 assert.match(await catalogRows.filter({has:page.getByText('Physics',{exact:true})}).innerText(),/1 task/);
 await page.getByLabel('New category',{exact:true}).fill(' physics ');await page.getByRole('button',{name:'Add category',exact:true}).click();assert.match(await page.locator('.category-notice').innerText(),/already available/);assert.equal(await catalogRows.count(),1);
 await page.getByLabel('Search study categories',{exact:true}).fill('Botany');assert.equal(await catalogRows.count(),1);assert.match(await catalogRows.innerText(),/From records/);
 await page.getByLabel('Search study categories',{exact:true}).fill('Physics');await page.getByRole('button',{name:'Delete category',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert((await data()).customCategories.includes('Physics'));
 await page.getByRole('button',{name:'Delete category',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();assert(!(await data()).customCategories.some(c=>c.trim().toLowerCase()==='physics'));assert.equal(await catalogRows.count(),1);assert.match(await catalogRows.innerText(),/From records/);
 await page.getByLabel('Search study categories',{exact:true}).fill('Topic 01');await page.getByRole('button',{name:'Delete category',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();assert.equal(await catalogRows.count(),0);
 await page.getByLabel('Search study categories',{exact:true}).fill('');await page.locator('#settings-categories').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/settings-catalog-desktop.png'});
 console.log('PASS Settings complete catalog, provenance, usage, duplicate feedback, cancel, and safe removal of used/unused custom categories');
 console.log('PASS Calendar task/event and manual log persistence, Timer catalog, paused-session protection, and category management shortcut');

 await go('tasks');await openTask();await category().click();await page.screenshot({path:out+'/category-menu-desktop.png'});
 const menu=page.getByRole('listbox');assert(await menu.evaluate(el=>el.scrollHeight>el.clientHeight));await menu.evaluate(el=>el.scrollTop=el.scrollHeight);await option('Topic 16').click();assert.equal(await category().innerText(),'Topic 16');
 await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
 await page.setViewportSize({width:390,height:844});await openTask();await category().click();await search().fill('Organic');await page.screenshot({path:out+'/category-menu-mobile.png'});
 const box=await page.getByRole('listbox').boundingBox();assert(box.x>=0 && box.x+box.width<=390 && box.y>=0 && box.y+box.height<=844);
 await option('Organic chemistry').tap();assert.equal(await category().innerText(),'Organic chemistry');assert.equal(await page.getByRole('listbox').count(),0);
 await category().click();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),1);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS long-list scrolling, mobile touch selection, bounded popup, nested Escape, and no browser errors');
} catch(error){await page.screenshot({path:out+'/failure.png'});console.error(error);process.exitCode=1;}finally{await browser.close();}
