import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright-core';
const base = process.env.TRACKME_URL || process.env.STUDYTRACK_URL || 'http://127.0.0.1:4174';
const output = '/tmp/trackme-history'; fs.mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, timezoneId: 'Asia/Kolkata', reducedMotion: 'reduce' });
page.setDefaultTimeout(10000);
const errors = []; page.on('pageerror', error => errors.push(error.message));
page.on('dialog', dialog => { errors.push('Native dialog: '+dialog.message()); dialog.dismiss(); });
const go = async route => { await page.goto(`${base}/${route}`); await page.locator('.route-frame').waitFor(); };
const data = () => page.evaluate(() => JSON.parse(localStorage.getItem('studytrack.workspace.v1')));
const select = async (name, option) => { await page.getByRole('combobox', { name, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click(); };
const clear = async () => page.getByRole('button', { name: 'Clear filters', exact: true }).click();
const exportRows = async () => {
  const pending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export CSV', exact: true }).click();
  const download = await pending; assert.match(download.suggestedFilename(), /^trackme-sessions-/);
  return fs.readFileSync(await download.path(), 'utf8').trim().split('\n');
};
try {
  await go('history');
  assert.equal(await page.title(), 'TrackMe');
  assert.equal((await (await page.request.get(base+'/site.webmanifest')).json()).short_name, 'TrackMe');
  assert.match(await page.locator('.sidebar').innerText(), /TrackMe/);
  assert(await page.getByRole('button', { name: 'Export CSV', exact: true }).isDisabled());
  await page.getByRole('button', { name: 'Log your first session', exact: true }).click();
  await page.getByRole('dialog').waitFor(); await page.keyboard.press('Escape');
  const today = await page.evaluate(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; });
  const seed = await data();
  seed.tasks = [{ id:'physics', title:'Physics review', description:'', status:'todo', priority:'medium', dueDate:today, plannedDate:today, createdAt:new Date().toISOString(), estimatedPomodoros:25, actualPomodoros:20, category:'Physics', subtasks:[] }];
  seed.sessions = Array.from({ length:22 }, (_, i) => ({ id:`session-${i}`, startTime:`${today}T${String(Math.floor(i/2)).padStart(2,'0')}:${i%2 ? '30' : '00'}:00+05:30`, endTime:`${today}T${String(Math.floor(i/2)).padStart(2,'0')}:${i%2 ? '40' : '10'}:00+05:30`, type:'focus', category:i===0?'Math':'Physics', taskId:i===0?undefined:'physics', actualDuration:10, plannedDuration:10, completed:i!==1, interrupted:i===1, source:i===2?'manual':undefined, notes:i===2?'Practice with diagrams':i===3?'Read with care':'' }));
  // The unchanged legacy namespace represents an existing installation before the rename.
  await page.evaluate(seed => localStorage.setItem('studytrack.workspace.v1', JSON.stringify(seed)), seed);
  await go('history');
  assert.equal((await data()).sessions.length, 22);
  assert.equal(await page.locator('.history-row').count(), 18);
  assert.match(await page.locator('.history-day-summary').innerText(), /18 of 22 sessions[\s\S]*220 min focus/);
  assert.equal((await exportRows()).length, 23);
  await page.getByRole('button', { name:'Next', exact:true }).click();
  assert.equal(await page.locator('.history-row').count(), 4);
  assert.match(await page.locator('.history-day-summary').innerText(), /4 of 22 sessions[\s\S]*220 min focus/);
  await select('History source', 'Manual log');
  assert.equal(await page.locator('.history-row').count(), 1);
  assert.match(await page.locator('.history-row').innerText(), /Manual log/);
  assert.match(await page.locator('.history-row').innerText(), /Practice with diagrams/);
  const rows = await exportRows(); assert.equal(rows.length, 2); assert.match(rows[1], /Physics review/);
  await clear(); await select('History outcome', 'Unfinished');
  assert.equal(await page.locator('.history-row').count(), 1);
  assert.match(await page.locator('.history-row .status-pill').innerText(), /Unfinished/);
  await clear(); await select('History subject', 'Math'); assert.equal(await page.locator('.history-row').count(), 1);
  await clear(); await page.getByRole('checkbox', { name:'With notes only' }).check(); assert.equal(await page.locator('.history-row').count(), 2);
  await page.getByLabel('Search history', { exact:true }).fill(' DIAGRAMS '); assert.equal(await page.locator('.history-row').count(), 1);
  await page.getByRole('button', { name:'Edit session notes', exact:true }).click();
  assert.match(await page.locator('.history-session-context').innerText(), /Physics review/);
  await page.getByRole('textbox', { name:'Session notes', exact:true }).fill('Updated revision notes');
  await page.getByRole('button', { name:'Save notes', exact:true }).click();
  assert.equal((await data()).sessions.find(s=>s.id==='session-2').notes, 'Updated revision notes');
  await page.getByText('No matching sessions', { exact:true }).waitFor();
  assert(await page.getByRole('button', { name:'Export CSV', exact:true }).isDisabled());
  console.log('PASS existing storage after rename, full-day totals across pages, complete filtered CSV, combined filters, and searchable note editing');

  await clear(); await page.getByRole('button', { name:'Custom', exact:true }).click();
  await page.getByLabel('History start date', { exact:true }).fill(today);
  await page.getByLabel('History end date', { exact:true }).fill(today);
  assert.equal(await page.locator('.history-row').count(), 18);
  await page.getByLabel('History end date', { exact:true }).fill('2020-01-01');
  await page.getByRole('alert').filter({ hasText:'Start date must be' }).waitFor();
  assert(await page.getByRole('button', { name:'Export CSV', exact:true }).isDisabled());
  await clear(); await select('History order', 'Oldest first');
  assert.match(await page.locator('.history-row').first().innerText(), /Math/);
  await page.getByRole('button', { name:'Delete session', exact:true }).first().click();
  await page.getByRole('alertdialog').getByRole('button', { name:'Cancel', exact:true }).click();
  assert.equal((await data()).sessions.length, 22);
  await page.getByRole('button', { name:'Delete session', exact:true }).first().click();
  await page.getByRole('alertdialog').locator('.confirm-submit').click();
  assert.equal((await data()).sessions.length, 21);
  await page.locator('.history-task-link').first().click();
  await page.getByRole('dialog', { name:'Task detail', exact:true }).waitFor();
  assert.equal(await page.getByLabel('Task title', { exact:true }).inputValue(), 'Physics review');
  await go('history'); await page.getByRole('button', { name:'Custom', exact:true }).click();
  await page.getByLabel('History start date', { exact:true }).fill(today);
  await page.getByLabel('History end date', { exact:true }).fill(today);
  await page.screenshot({ path:`${output}/history-desktop.png`, fullPage:true });
  console.log('PASS custom dates and validation, ordering, confirmation-based deletion, and linked task navigation');

  await page.setViewportSize({ width:390, height:1000 });
  assert.equal(await page.locator('.main-panel').evaluate(el=>el.scrollWidth>el.clientWidth), false);
  await select('History source', 'Manual log');
  assert.equal(await page.locator('.history-row').count(), 1);
  await page.screenshot({ path:`${output}/history-mobile.png`, fullPage:true });
  await page.getByRole('button', { name:'Edit session notes', exact:true }).click();
  assert.equal(await page.getByRole('dialog').evaluate(el=>el.scrollWidth>el.clientWidth), false);
  await page.screenshot({ path:`${output}/notes-mobile.png` }); await page.keyboard.press('Escape');
  await go('settings');
  const pendingBackup = page.waitForEvent('download');
  await page.getByRole('button', { name:'Export', exact:true }).click();
  const backup = await pendingBackup;
  assert.match(backup.suggestedFilename(), /^trackme-backup-/);
  const saved = JSON.parse(fs.readFileSync(await backup.path(), 'utf8'));
  assert.equal(saved.sessions.length, 21);
  await page.locator('input[type=file]').setInputFiles({ name:'studytrack-old-backup.json', mimeType:'application/json', buffer:Buffer.from(JSON.stringify(seed)) });
  await page.getByRole('alertdialog').locator('.confirm-submit').click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('studytrack.workspace.v1')).sessions.length===22);
  assert.equal((await data()).tasks[0].title, 'Physics review');
  assert.deepEqual(errors, []);
  console.log('PASS TrackMe metadata and backup filenames, and old StudyTrack backup import');
  console.log('PASS mobile filters, notes dialog, responsive layout, and no browser errors');
} catch(error) { await page.screenshot({ path:`${output}/failure.png`, fullPage:true }); console.error(error); process.exitCode=1; }
finally { await browser.close(); }
